spring.application.name=file-storage-service
server.port=8083

file.storage.path=${FILE_STORAGE_PATH:/files}

logging.level.root=INFO
logging.logstash.host=${LOGSTASH_HOST:localhost}
logging.logstash.port=${LOGSTASH_PORT:5000}