server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: car-service
              uri: http://car-service:8081
              predicates:
                - Path=/api/cars/**

logging:
  level:
    root: INFO
  logstash:
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5000}